"""production_date nullable

Revision ID: 95e044df8837
Revises: 65b4551f2f68
Create Date: 2021-12-05 00:03:39.270921

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "95e044df8837"
down_revision = "65b4551f2f68"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cars", "production_date", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cars", "production_date", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    # ### end Alembic commands ###
